// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hheblewffuzdyxiysfry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZWJsZXdmZnV6ZHl4aXlzZnJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2Nzk5MDEsImV4cCI6MjA3MzI1NTkwMX0.WnfsMnRiFcIiTr-rk8obkenTPSZhYbL8QoWfwworquw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});